"""8

Revision ID: 558dd152a55a
Revises: 0c246fbe6369
Create Date: 2025-05-22 22:41:40.157364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558dd152a55a'
down_revision: Union[str, None] = '0c246fbe6369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'folders', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'creator_id')
    # ### end Alembic commands ###
