"""900

Revision ID: a5adb26af0cc
Revises: 7c256d1c02af
Create Date: 2025-06-21 14:53:02.101616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5adb26af0cc'
down_revision: Union[str, None] = '7c256d1c02af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonses', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'anonses', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anonses', type_='foreignkey')
    op.drop_column('anonses', 'creator_id')
    # ### end Alembic commands ###
