"""9

Revision ID: ea5731b510eb
Revises: 558dd152a55a
Create Date: 2025-05-22 23:25:32.454688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5731b510eb'
down_revision: Union[str, None] = '558dd152a55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'files', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'creator_id')
    # ### end Alembic commands ###
